// OpenCode v2 adapter for Graphify (Local AI Infra).
//
// Managed by `scripts/bootstrap` from templates/opencode/plugins/graphify.ts;
// edit the template, not this installed file. It registers a one-time
// navigation reminder and never hardcodes a graph path: the canonical graph is
// published by Multi-Machine Sync in the runtime descriptor
// `$LAI_STATE_DIR/graphify/runtime.json` (default
// `~/.local/state/local-ai-infra/graphify/runtime.json`), which is generated by
// `scripts/bootstrap apply` from the same `graphify.graph_dir` semantics used by
// `bootstrap graph status`/`graph rebuild`. If the descriptor is absent this
// adapter writes nothing and injects no reminder.

import { existsSync, readFileSync } from "node:fs"

function stateDir(): string {
  if (process.env["LAI_STATE_DIR"]) return process.env["LAI_STATE_DIR"] as string
  return `${process.env["HOME"]}/.local/state/local-ai-infra`
}

function canonicalGraph(): string | null {
  const override = process.env["GRAPHIFY_GRAPH"]
  if (override) return override
  const descriptor = `${stateDir()}/graphify/runtime.json`
  try {
    if (!existsSync(descriptor)) return null
    const data = JSON.parse(readFileSync(descriptor, "utf8"))
    const path = data?.graph_path
    return typeof path === "string" && path ? path : null
  } catch {
    return null
  }
}

// One reminder per OpenCode session (not per hook call).
const reminded = new Set<string>()

export default {
  id: "graphify",
  async setup(ctx: any) {
    await ctx.tool.hook("execute.before", (event: any) => {
      try {
        const tool = String(event?.tool ?? "").toLowerCase()
        if (tool !== "shell" && tool !== "bash") return

        const sessionID = String(event?.sessionID ?? "")
        if (sessionID && reminded.has(sessionID)) return

        const input = event?.input
        if (!input || typeof input !== "object") return

        const command = (input as Record<string, unknown>).command
        if (typeof command !== "string" || !command) return

        const graph = canonicalGraph()
        if (!graph || !existsSync(graph)) return
        if (sessionID) reminded.add(sessionID)

        // Single-quoted echo (no inner quotes/backticks/$()) so the shell and
        // RTK's own rewrite of the trailing command are unaffected.
        const reminder =
          `echo '[graphify] local knowledge graph available. For codebase/architecture ` +
          `questions prefer: graphify query <question> --graph ${graph} (scoped subgraph) ` +
          `over grepping raw files.' ; `
        ;(input as Record<string, unknown>).command = reminder + command
      } catch (err) {
        // A Graphify failure must never fail the user's shell command.
        console.warn(
          `[graphify] reminder skipped: ${err instanceof Error ? err.message : String(err)}`,
        )
      }
    })
  },
}
